### PR TITLE
Changed portals so they lead to each other instead of dumping player at respawn/spawn

### PR DESCRIPTION
**Pull request by Rimevel**
With this change portals are now tile entities that manage their destination by themselves. When inserting a key in a keyhole, the generated portals in both dimensions are given their destination in the opposite.

### CODE REVIEW

**Comment by AllenSeitz** [comment]
Off the top of my head though, what about the rooms with alternate exit portals? I only have two right now. I guess I can take those alternate exits out. (And actually magicpuzzle_1, the frost walker igloo room, is temporarily out of the rotation for another bug.)

**Comment by Rimevel** [comment]
Rooms with alternate exit portals should be fine. I did not run into any during my testing, but all exit portals, no matter where they are in the dungeon, should work the exact same way.

**Comment by Rimevel** [comment]
Also if you dont plan to use the capability stuff, it can probably be cleaned up/removed since this does not touch that in any way.

**Review by AllenSeitz — COMMENTED** [review]
This seems to be working! And your changes look good.

There is an issue with reopening portals to old dungeons. The gold portal blocks aren't relinked to the new coordinates. I'm currently testing a fix for this minor issue, then I'll remove the other alternate exit so that it isn't a problem. Would you mind if I put a sign thanking Rimevel somewhere in the dungeon?

**Comment by Rimevel** [comment]
Ah right, I did not consider the fact that you can re-open the portal elsewhere *facepalm*
Sorry for that oversight. I hope its easy to fix. I will be interested to see how you solve that.
As for credit to any contributors, maybe a secret credits room (broken wall instead of door) that sometimes spawn? That could be cool :D

**Comment by AllenSeitz** [comment]
Yeah it was simple. Since the key itself knows the coordinates to teleport the player to all I have to do is look at the arrival position, zpos + 2, xpos -0 and -1, and ypos range [55..57], and I know where the 6 return portal blocks are. Seems to be working great!

Back to working on 1.09. I'll include this change in that version.

**Pull request merged**
